### ISSUE TITLE
[Evaluation] Update AP interpolation method

### ISSUE THREAD

**Issue by cabaf** [activitynet/ActivityNet#1]
The current version of the code uses the 11-point interpolation method. This measure was used in the PASCAL VOC challenge up to the 2008 edition. In the newer versions of Pascal VOC the interpolation method is following this code: [https://github.com/npinto/VOCdevkit/blob/master/VOCcode/VOCap.m](https://github.com/npinto/VOCdevkit/blob/master/VOCcode/VOCap.m).

Required actions:

- Update the function `interpolated_prec_rec` to act in the same way of [VOCap.m](https://github.com/npinto/VOCdevkit/blob/master/VOCcode/VOCap.m)

**Comment by escorciav** [comment]
Update [this function](https://github.com/activitynet/ActivityNet/blob/master/Evaluation/utils.py#L14)

**Comment by escorciav** [comment]
This mini-test was passed succesfully. Feel free to close it, after a more realistic test :wink: 

[Matlab version](http://goo.gl/JJLCft) against the following script

```python
import numpy as np

from utils import interpolated_prec_rec


prec = np.array([0, 1, 0.5, 0.2, 0.1])
rec = np.array([0, 0.1, 0.5, 0.8, 1])
ap = interpolated_prec_rec(prec, rec)
print ap
```
