### ISSUE TITLE
conda : solving environment failed !!

### ISSUE THREAD

**Issue by sebyo** [activitynet/ActivityNet#101]
I followed the instructions to download the kinetics dataset but when I tried to create the environment error message occures olving environment : failed PackageNotFound Error : the following packages are not available from current channels to search for alternate channels that may provide conda package your looking for navigate to http:// anaconda.org 
I used this to create it : conda create -n env -f environment.yml
and I am using windows 10.
any help @HumamAlwassel  thank you!!

**Comment by HumamAlwassel** [comment]
Download kinetics dataset from here
https://github.com/cvdfoundation/kinetics-dataset

Cheers!

**Comment by sebyo** [comment]
thank you for your reply
