### ISSUE TITLE
not working on downloading

### ISSUE THREAD

**Issue by Hayeon-kimm** [activitynet/ActivityNet#103]
I can't apply the format for downloading datasets.
Here : https://docs.google.com/forms/d/e/1FAIpQLSeKaFq9ZfcmZ7W0B0PbEhfbTHY41GeEgwsa7WobJgGUhn4DTQ/closedform

**Comment by escorciav** [comment]
Contact shuming from KAUST - IVUL group

**Comment by escorciav** [comment]
or @Soldelli @PardoAlejo

**Comment by sming256** [comment]
The link of request form has changed to [https://docs.google.com/forms/d/e/1FAIpQLSdxhNVeeSCwB2USAfeNWCaI9saVT6i2hpiiizVYfa3MsTyamg/viewform](https://docs.google.com/forms/d/e/1FAIpQLSdxhNVeeSCwB2USAfeNWCaI9saVT6i2hpiiizVYfa3MsTyamg/viewform)

Sorry for the inconvenience. @escorciav @Hayeon-kimm
