### ISSUE TITLE
annotations of test set

### ISSUE THREAD

**Issue by zed0630** [activitynet/ActivityNet#11]
Hello,
I'm downloading the Kinetics dataset currently, but I cannot find annotations of test set. Do I miss anything or the test file with annotations has not been released yet?
Also, as it is reported in the paper "Quo Vadis, Action Recognition? A New Model and the Kinetics Dataset" by Joao Carreira and Andrew Zisserman, there is a subset of Kinetics dataset called miniKinetics, which may help to both reduce time consumption and computation resource usage. So could you please tell me how to get the CSV files of miniKinetics? 
Thanks!

**Comment by HumamAlwassel** [comment]
Thanks for your interest in ActivityNet Challenge. The Kinetics test subset is not released for the purposes of holding future ActivityNet Challenges in CVPR. Please use the [2017 ActivityNet Challenge Evaluation Server](http://activity-net.org/challenges/2017/evaluation.html) to evaluate your method on the test subset. Unfortunately, the ActivityNet Challenge organizers do not have the CSV files of miniKinetics. Please contact the researchers at DeepMind (the authors of the paper you mentioned) for those specific files.
Cheers!
