### ISSUE TITLE
模型咨询

### ISSUE THREAD

**Issue by pardy218** [activitynet/ActivityNet#12]
ActivityNet代码有吗，我现在想学习一下

**Comment by HumamAlwassel** [comment]
I'm sorry I cannot understand your issue. Could you please write it in English?

**Comment by erikdao** [comment]
@pardy218 你能用英文发表你的问题吗？

**Comment by pardy218** [comment]
ok,Can you provide code for activityNet, I want to learn to learn.

**Comment by HumamAlwassel** [comment]
This [https://github.com/activitynet/ActivityNet](repository) contains all our ActivityNet code:
- code for downloading the dataset [in /Crawler/ folder]
- code for evaluating each task of the ActivityNet Challenge [in /Evaluation/ folder]
- notebooks for visualizing details about the dataset and baselines for the challenge tasks [in /Notebooks/ folder]
