### ISSUE TITLE
Am l allowed to use the crawler to download all the kinetics dataset ?

### ISSUE THREAD

**Issue by pinkfloyd06** [activitynet/ActivityNet#13]
Hello,

l'm wondering whether, we can download all the dataset.
In other term, in order to avoid that my IP adress will be blocked, how much videos can l download ?

Thank you

**Comment by HumamAlwassel** [comment]
Hello! Thank you for your interest in ActivityNet. From our experience, no user reported that they were blocked after downloading kinetics.
Best,
Humam
