### ISSUE TITLE
All videos in the ActivityNet training set are unavailable on Youtube as of 2018-03-06

### ISSUE THREAD

**Issue by Enamex** [activitynet/ActivityNet#18]
All videos are reporting download errors using the downloader script in this repo. We tried accessing some by hand from Youtube and they report the same error as `youtube-dl` (as they should, sadly).

The error is invariably

> This video is unavailable.

Example:
![image](https://user-images.githubusercontent.com/5769148/36978056-f6ffadc0-208b-11e8-97a4-0f7236fdac34.png)

**Update**: All training videos are unavailable.

**Comment by lucasb-eyer** [comment]
I was able to download almost all of the videos over the past couple weeks. Maybe you are using a too old version of `youtube-dl`.

**Comment by HumamAlwassel** [comment]
Hi @Enamex,

Sorry for the delayed response - we were busy with ECCV. We know that around 1k videos of ActivityNet are unavailable on YouTube now, but the other 19k videos are still up. Are you still unable to download the videos? 

**Possible reasons we collected from previous users for why they cannot download some videos:**
- _Problem_: an old version of `youtube-dl`; _Solution_: update to the latest version.
- _Problem_: blocked by country; _Solution_: use VPN to download (if possible VPN into the US for best results)
- _Problem_: video removed by YouTube or by the content creator (currently there is around 1k of those); _Solution_: email us the YouTube IDs.


Humam

**Comment by lucasb-eyer** [comment]
"The other 19k" only covers the val-set, though, right?

As an additional datapoint, I was able to download 232264 videos from the train-set without problems, and 14270 had problems (9020 "unavailable" and 4247 "account terminated", the rest various other causes). The VPN is a good idea, I will give that a try in order to get most (hopefully) remaining videos, as YouTube does block a lot in Germany.

**Comment by HumamAlwassel** [comment]
@lucasb-eyer I think you are referring to the Kinetics dataset. The original question (and my answer) are about the ActivityNet dataset.

**Comment by lucasb-eyer** [comment]
Oh, you are right, very sorry for this mixup and distracting from the OP. :blush:
