### ISSUE TITLE
Speed about download.py

### ISSUE THREAD

**Issue by wangzhangup** [activitynet/ActivityNet#22]
When I modified the line 104 'libx264' as 'copy', the speed of getting video files became super fast....

why use 'libx264'?

**Comment by escorciav** [comment]
Good point. What about the space?

**Comment by wangzhangup** [comment]
Train dataset use about 311G.

**Comment by escorciav** [comment]
Thanks for the information. I will close the issue given that this trick was already mentioned [here](https://github.com/activitynet/ActivityNet/pull/16).

**Comment by zhujingsong** [comment]
@wangzhangup How fast is your download speed? Do you use VPN?

**Comment by wangzhangup** [comment]
@zhujingsong No VPN! I bought a VPS on DigitalOcean.
