### ISSUE TITLE
Update kinetics data

### ISSUE THREAD

**Issue by escorciav** [activitynet/ActivityNet#24]
Due to the recent update in Kinetics-600 we must update the files.

**Comment by gurkirt** [comment]
What do you mean? Do we have to download the files again or just check filenames in downloaded files and put them in correct folders?

**Comment by escorciav** [comment]
Hi @gurkirt,

- in principle just putting them in the correct folders.
- However, it will take less than 10-30mins to run the `download.py` again pointing to the same folders where you already placed the data. I would do this I'm going for the first prize 😉.

All the best,
Victor

**Comment by gurkirt** [comment]
Thanks for the quick prize (response) :) I was just wondering it wouldn't mess up kinetics-400 dataset.

**Comment by escorciav** [comment]
I was talking about Kinetics-600 data.

_Historical note (don't read it - you have important things to do)_
I did a crude attempt, at 2-3 am, to not download videos from K-600 already downloaded for K-400. The numbers did not sum up and the logic is too cumbersome. I deferred to Fabian who is in direct contact with Joao. We decided to let this option to the user because it's an overhead to maintain untidy code, and we only count with the same information provided to the participants.

**Comment by gurkirt** [comment]
Actually, there is class name discrepancy in both versions. Some classes that are there in 400 but not in 600. I think they changed the name of classes or merged some classes or split some classes, IDK.  Also renamed passing American football (not in game) with capital A. here are the names of the classes that are there in 400 but not in 600 with the number of videos. 

cooking sausages 352
cleaning floor 743
filling eyebrows 896
garbage collecting 334
riding mountain bike 384
skiing (not slalom or crosscountry) 1003
tossing salad 350
shredding paper 294
drinking beer 451
making bed 559
using computer 795
taking a shower 265
balloon blowing 668
gargling 311
exercising arm 310
passing American football (not in game) 915
cooking chicken 847
drinking 477
label 0
opening bottle 608
strumming guitar 359
spraying 365
swinging legs 302
digging 299
dying hair 892
tying tie 554
changing wheel 350
playing cards 618
baby waking up 494
throwing ball 519
hugging 395
sniffing 291

**Comment by escorciav** [comment]
That's why my numbers did not match. Thanks!

**Comment by escorciav** [comment]
The challenge is almost done and due to the incident with the test dat,  we consider pertinent to update the files to smooth things out.
Thanks @cabaf
