### ISSUE TITLE
Nothing is downloaded with Kinetics-400 

### ISSUE THREAD

**Issue by cryptedp** [activitynet/ActivityNet#25]
Hi 
I am trying to download videos and I use the command : 
python download.py data/kinetics-400_train.csv /data/sammer/Kinetics
However no videos are downloaded, the directories are created but there are no videos inside. Is that an issue with youtube or should I just use the other csv file ?

**Comment by escorciav** [comment]
hi @cryptedp!
That's weird. After the update, I made sure that the code was working for kinetics-400. I can double check tomorrow when I get access to my workstation.

- What kind of messages do you see in the `progress_report.json`?

> Is that an issue with youtube or should I just use the other CSV file?

I don't know what you mean. If you need to download Kinetics-400. You should use that file. If you need kinetics-600, use the other file.

Sorry if I'm not very helpul today.
I will keep an eye on this to see if I can give you tips for debugging.

**Comment by cryptedp** [comment]
Ah found the error, apparently, youtube-dl was not installed (there was an error in the progress report only..). Now it works, thanks :+1:

**Comment by escorciav** [comment]
Glad that you found the error. I will close the issue in that case.

**Comment by zhujingsong** [comment]
@cryptedp I am faced with the same problem, how did you solve it ???

**Comment by Ai-is-light** [comment]
@cryptedp @escorciav I have succeed in installing the youtube-dl and the requirement environment, but I still not worked. I
I run 
(kinetics) ➜  Kinetics git:(master) ✗ python2.7 download.py ./data/kinetics-400_train.csv ./kinetics-dataset/train-400
this code would produce the many folders under the path ./kinetics-dataset/train-400
however, it didn't download anything, although it worked more than one night.
Looking forward to any replies

**Comment by Ai-is-light** [comment]
@escorciav where can I got the progress_report.json ?

**Comment by khaerulumam42** [comment]
@Ai-is-light `progress_report.json` file generated on same folder with `dowload.py` file
