### ISSUE TITLE
how to download Kinetics dataset?

### ISSUE THREAD

**Issue by git-sohib** [activitynet/ActivityNet#26]
@cabaf 
I am trying to download this dataset to work with [this project](https://github.com/kenshohara/video-classification-3d-cnn-pytorch) but I cant do it. Could you please give some detailed instructions on how to download this dataset. When I type `conda env create -f environment.yml ` in **ActivityNet\Crawler\Kinetics** path I get this error:
```
Solving environment: failed

ResolvePackageNotFound:
  - readline==6.2=2
  - openssl==1.0.2k=1
  - ffmpeg==3.1.3=0
  - zlib==1.2.8=3
  - sqlite==3.13.0=0
  - tk==8.5.18=0
```

And,
I don't understand this part at all
`mkdir <data_dir>; python download.py {dataset_split}.csv <data_dir>`
BTW, I am on Windows 10 
Thank you

**Comment by escorciav** [comment]
Sorry, we write the code for Linux.

That creates a directory where you will find the videos after running the `download.py` program.

**Comment by blankWorld** [comment]
hello，how much hard disk space can hold downloaded Kinetics dataset ？

**Comment by escorciav** [comment]
around 0.7-0.9TB.
Please double check in the google forum of activitynet. Another user asked the same question.

**Comment by MuchaoYe** [comment]
Hello, I have a question on the code `mkdir <data_dir>; python download.py {dataset_split}.csv <data_dir>` 
I cannot figure what does `{dataset_split}.csv` reference to, could you explain it to me?
Thank you!

**Comment by l2009312042** [comment]
why don't give a downloaded video set  to download ?

**Comment by escorciav** [comment]
Thanks for the suggestion. Please share it with the maintainers of the [dataset](https://deepmind.com/research/open-source/open-source-datasets/kinetics/). We only host toolkits for the ActivityNet Challenge.
I will close this issue because the conversation has deviated to other topics.

**Comment by gitumarkk** [comment]
@escorciav following up on hosting the video datasets. Are there legal implications to hosting the datasets? This is because i want host them on my own s3 buckets to make them easier for people to download as fetching them from Youtube can be frustrating especially with the new download limits in place.

**Comment by escorciav** [comment]
*Please be noticed that anything that you or others do is your sole responsibility.*

That said. I have seen other academic groups do it for other datasets from Youtube.  Thus, that's certainly an option. Be careful of stating (at least) these items to the public:

1. The videos are hosted solely for academic purposes. Any other use is governed by the license of the owner and Youtube.

2. Any video will be removed without further delay if the owner raised a complaint.

3. The data is provided as it is and there is no responsibility for its misuse, of any damage. Copy that part from any standard license like Creative Commons.

That concluded what I have seen. I am not responsible for any action taken by another individual or group of individual in regard to the observations shared here.

**Comment by gitumarkk** [comment]
@escorciav thank you, will keep what you have said in mind and I understand they are just observations and you bear no responsibility.

**Comment by escorciav** [comment]
Just remind that there are alternatives like [academic torrent](http://academictorrents.com/) where people can help each other for academic purposes.

Just saying. I haven't tried it before, but the guys are pretty responsive replying to emails.

**Comment by gitumarkk** [comment]
@escorciav thanks for your help, wasn't aware about it and will check it out.

**Comment by busixingxing** [comment]
I am not able to download the dataset after a few successful video downloaded either. I am using Pytube instead of youtube_dl.
