### ISSUE TITLE
Nothing is downloaded

### ISSUE THREAD

**Issue by zhujingsong** [activitynet/ActivityNet#29]
I checked every step as the instructions, and the environment seems 'right:'
(kinetics) svc7@omnisky-SYS-7048GR-TR:~/ActivityNet/Crawler/Kinetics$ conda list
# packages in environment at /home/svc7/anaconda3/envs/kinetics:
#
# Name                    Version                   Build  Channel
decorator                 4.0.11                    <pip>
ffmpeg                    3.1.3                         0    menpo
joblib                    0.9.4                    py27_0    defaults
mkl                       2017.0.1                      0    defaults
numpy                     1.12.1                   py27_0    defaults
olefile                   0.44                      <pip>
openssl                   1.0.2k                        1    defaults
pandas                    0.19.2              np112py27_1    defaults
pip                       9.0.1                    py27_1    defaults
python                    2.7.13                        0    defaults
python-dateutil           2.6.0                    py27_0    defaults
pytz                      2017.2                   py27_0    defaults
readline                  6.2                           2    defaults
setuptools                27.2.0                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
youtube-dl                2018.6.4                  <pip>
zlib                      1.2.8                         3    defaults

But when I run download.py data/kinetics-400_train.csv /data/zjs/kinetics
All the directories (class_names) are generated, but no video (0) has been download.
I tried several times, but it is still the same problem. I am wondering if you could give some advice??

**Comment by Ai-is-light** [comment]
@zhujingsong Have you succeed in downloading this dataset? I meet the same error as you.
Looking forward any replies.
Thanks

**Comment by khaerulumam42** [comment]
I have some problem, i check the data have downloaded in `/tmp/kinetics` but after I reboot the folder gone and no data downloaded to spesific folder. How you to solve this problem?

**Comment by jeff62802217** [comment]
> I have some problem, i check the data have downloaded in `/tmp/kinetics` but after I reboot the folder gone and no data downloaded to spesific folder. How you to solve this problem?

I have the same problem, have you already solved that problem?

**Comment by saniazahan** [comment]
The same thing is happening with me as well. Anyone got any solutions?
