### ISSUE TITLE
Classes of ActivityNet

### ISSUE THREAD

**Issue by antran89** [activitynet/ActivityNet#3]
Hi the organizers,
I want to explore ActivityNet dataset. I am running to the problem of classes of ActivityNet dataset, because we only know classes of a video by looking at json file annotation.
I want a standard classes.txt for cross-checking and also use as a 'numerical' category for training a CNN.
Best regards,

**Comment by antran89** [comment]
Is there any tools to visualize the taxonomy tree? Thanks @cabaf @escorciav

**Comment by antran89** [comment]
Thank you for your help. I am writing scripts to extract class names of ActivityNet datasets. You can find [here](https://github.com/antran89/ActivityNet/tree/master/Crawler). Because I did not receive any feedback for the request, I close the issue.

**Comment by escorciav** [comment]
Hi @antran89, sorry for the late reply.

I don't consider that it's critical to provide a text file with the category names. JSON is a standard format, and it is easy to retrieve the classes. Thanks for showing how to do that with Python 😉.

Regarding the question about the taxonomy tree, Fabian explained how to traverse the tree [here](http://activity-net.org/download.html). Code for visualization might exist, but it may not be polished.

**Comment by mangdian** [comment]
@escorciav  I just parsed the json file and get the class number id of activitynetv1.2
`"Preparing pasta",186
"Bathing dog",90
"Discus throw",92
"Playing field hockey",94
"Grooming horse",95
"Snatch",79
"Preparing salad",96
"Playing harmonica",100
"Chopping wood",110
"Playing saxophone",109
"Washing face",113
"Using the pommel horse",114
"Javelin throw",116
"Spinning",117
"Ping-pong",119
"Making a sandwich",129
"Brushing hair",125
"Playing water polo",130
"Doing step aerobics",230`

However, there are only 100 classes in ActivityNet V1.2. The class number id shall be samller than 100. How should I use this id list for training?

**Comment by escorciav** [comment]
Hi!
- The number of categories in v1.2 is 100. Please take a look at the description [here](http://activity-net.org/download.html).
- The ID was generated for another purpose. Feel free to use your own indexing for training purposes.
- If you are interested in submitting results to the evaluation server, take a look at the description [here](http://activity-net.org/challenges/2017/localization.html) for temporal action localization, and [here](http://activity-net.org/challenges/2017/untrimmed.html) for untrimmed video classification. Please note that we don't use the ID of the activity to parse results.
Warmly,
Victor

**Comment by wwdok** [comment]
I 

> Thank you for your help. I am writing scripts to extract class names of ActivityNet datasets. You can find [here](https://github.com/antran89/ActivityNet/tree/master/Crawler). Because I did not receive any feedback for the request, I close the issue.

Great ! i finally find what i want !

**Comment by ererdewubudesi** [comment]
> Thank you for your help. I am writing scripts to extract class names of ActivityNet datasets. You can find [here](https://github.com/antran89/ActivityNet/tree/master/Crawler). Because I did not receive any feedback for the request, I close the issue.

Thanks a lot!!! It‘s helpful.
