### ISSUE TITLE
Nothing is downloaded with Kinetics-400!!!

### ISSUE THREAD

**Issue by Ai-is-light** [activitynet/ActivityNet#30]
@escorciav Thanks for you good work
I have succeed in installing the youtube-dl and the requirement environment, but I still not worked. And
I run
(kinetics) ➜ Kinetics git:(master) ✗ python2.7 download.py ./data/kinetics-400_train.csv ./kinetics-dataset/train-400
this code would produce the many folders under the path, ./kinetics-dataset/train-400
however, it didn't download anything, although it worked more than one night.
Looking forward to any replies

**Comment by escorciav** [comment]
Sorry to hear that. However, I can't debug what's going on on your machine. Othe people had similar complains,

- did you read all the previous issues with similar problems?

- if none of those it's your case, I would suggest debugging what's going on running each line at a time. If you set `-n/--num-jobs` to 1, you will disable multiprocessing. That should make debugging trivial for a python programmer.

I will keep the issue open in case there is an actual bug in the code.

**Comment by escorciav** [comment]
I will close this issue as it has been a while. Feel free to keep the discussion here.
