### ISSUE TITLE
About the program stuck

### ISSUE THREAD

**Issue by Smicon** [activitynet/ActivityNet#31]
Thank you very much for your code. I can't wait to use it, but when I am executing this line of code:
`python download.py  data/kinetics-400_test.csv data_dir`
It has been executed all the time, and there are no displays or errors. It still works like a night. So I debug download.py and I found that the program card is on the method corresponding to the two objects imported from joblib. How should I deal with this situation?

**Comment by ahmedshoaib** [comment]
> Sorry to hear that you are facing troubles to get the data.
> 
>     * In case, you have difficulties debugging with joblib and multiprocessing, follow the advice that I mentioned in [this issue](#30)
> 
>     * Please search previous issues of people with similar issues. In many cases, they realized that they weren't using the program appropriately.

The link for the advice on joblib isn't functional

**Comment by escorciav** [comment]
edited

**Comment by escorciav** [comment]
I will close this issue as it has been a while. Feel free to keep the discussion here.
