### ISSUE TITLE
Extract RGB frames from videos

### ISSUE THREAD

**Issue by sophia-wright-blue** [activitynet/ActivityNet#33]
Hello,

Thank you for making this dataset available. Could you point me to a repo/script that I can use to extract every nth RGB frame from the videos in the dataset?

Thanks,

**Comment by escorciav** [comment]
Maybe, you could grab something useful of [this repo](https://github.com/escorciav/video-utils/) that I maintain. It lacks documentation, thus you may need to read between lines.
- the program for extracting frames is [here](https://github.com/escorciav/video-utils/blob/master/tools/batch_dump_frames.py). Take care with the caveat of using that program with [joblib and -n > 1](https://github.com/escorciav/video-utils/issues/2)
