### ISSUE TITLE
Data is not downloading!

### ISSUE THREAD

**Issue by BarakBat** [activitynet/ActivityNet#35]
Hi data is not downloading, not with 400, and not with 600, don't send me to another post because I saw all of them, and no one solved the problem. and my youtube-dl is installed correctly.
I'm using this line:
` python3 download.py data/kinetics-400_train.csv kinetics-400_train/` 
and nothing happens, stuck, no error, no warning, I didn't even get this file:
progress_report.json

Please help.

**Comment by escorciav** [comment]
Hi! we are sorry to hear that.
Please note that you are not using the appropriate environment because you are calling it with python3. I already mentioned [here](https://github.com/activitynet/ActivityNet/issues/34), that the code was written for python-2.

For troubleshooting, I would use the following command:
`python -m pdb download.py data/kinetics-400_train.csv kinetics-400_train/ --num-jobs 1` 
The command above:
- disables multiprocessing of joblib due to `--num-jobs 1`. This was already mentioned [here](https://github.com/activitynet/ActivityNet/issues/30).
- invokes the command line python debugger `-m pdb`.

For more details about how to use the python debugger, there are plenty of tutorials reachable with google or youtube. For example [1](https://realpython.com/python-debugging-pdb/) or [2](https://www.youtube.com/watch?v=bZZTeKPRSLQ).

**Comment by BarakBat** [comment]
I tried also with python2.7, it's downloading to the /tmp directory, does that gives you a hint on the problem?
I will try also the recommendations you gave.

**Comment by escorciav** [comment]
Great, that suggests that the youtube-dl is working. Try to reach the [part](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/download.py#L98-L113) related with launching processes with `FFmpeg` (via subprocess).
While I'm debugging this kind stuff, I usually:
1. reach that line `> b 111`.
  It tells to `pdb` to stop at line 111 of the code.
2. type `> print(command)` to see the process that I'm about to launch.
  It tells to `pdb` to print command.
3. Copy the command printed and type it in a new shell.
  If it does not work, it means there is something wrong either with `FFmpeg` or the command.
Good luck!

**Comment by BarakBat** [comment]
I will try that.
I thought about changing the tmp path, does it matter for the dataset that all the videos download to one directory, or the splitting to directories is important?

**Comment by jhagege** [comment]
I had the same issue and solved it by running the following instructions (from Kinetics README):
```
conda env create -f environment.yml
source activate kinetics
pip install --upgrade youtube-dl
```

**Comment by BarakBat** [comment]
Thanks my friend, I have a weird thing, the script is creating the directories, but the videos are downloaded outside the directories, means all the videos to one directory, no splitting, is it suppose to be like this?

**Comment by jhagege** [comment]
Not sure about that.
I forgot to mention I used the fork of jremmons which downloads only part of the files with ffmpeg (from URL) and reencodes: https://github.com/jremmons/ActivityNet

**Comment by BarakBat** [comment]
> Great, that suggests that youtube-dl is working. Try to reach the [part](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/download.py#L98-L113) related with launching `FFmpeg` editing (via subprocess).
> While I'm debugging this kind stuff, I usually:
> 
> 1. reach that line `> b 111`.
>    It tells to `pdb` to stop at line 111 of the code.
> 2. type `> print(command)` to see the process that I'm about to launch.
>    It tells to `pdb` to print command.
> 3. Copy the command printed and type it in a new shell.
>    If it does not work, it means there is something wrong either with `FFmpeg` or the command.
> 
> Good luck!

Hi I tried to debug , when I reach 111 and try to print command he's telling me :
"name 'command' is not defined", while I can see in the file in my computer, that command been assigned, maybe that helps t understand the problem?

**Comment by escorciav** [comment]
That's really weird, honestly I'm clueless and don't know how to help you. In your situation, I would just start again from scratch:
- Clone the repository in a new folder

- Create a new conda environment

- Delete the `tmp-dir` which by default is `/tmp/kinetics`

- Run the code as I mentioned [here](https://github.com/activitynet/ActivityNet/issues/35#issuecomment-432024434)

In a nutshell, try to replicate your error from scratch.

**Comment by escorciav** [comment]
I will close this issue as it has been a while. Feel free to discuss below.

**Comment by jeff62802217** [comment]
> > Great, that suggests that youtube-dl is working. Try to reach the [part](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/download.py#L98-L113) related with launching `FFmpeg` editing (via subprocess).
> > While I'm debugging this kind stuff, I usually:
> > 
> > 1. reach that line `> b 111`.
> >    It tells to `pdb` to stop at line 111 of the code.
> > 2. type `> print(command)` to see the process that I'm about to launch.
> >    It tells to `pdb` to print command.
> > 3. Copy the command printed and type it in a new shell.
> >    If it does not work, it means there is something wrong either with `FFmpeg` or the command.
> > 
> > Good luck!
> 
> Hi I tried to debug , when I reach 111 and try to print command he's telling me :
> "name 'command' is not defined", while I can see in the file in my computer, that command been assigned, maybe that helps t understand the problem?
> 
> Edit , I wrote some debugging line in the file, and got this command:
> command_['ffmpeg', '-i', '"LICENSE"', '-ss', '59', '-t', '10', '-c:v', 'libx264', '-c:a', 'copy', '-threads', '1', '-loglevel', 'panic', '"kinetics-400_train/abseiling/-3B32lodo2M_000059_000069.mp4"']
> 
> ['ffmpeg', '-i', '"LICENSE"' -->that's doesn't seem right...
> 
> And when I'm printing tmp_filename file I'm getting this:
> ./b5bd7601-b87b-49b2-9ad6-c6311c915e85.%(ext)s

Hey guy!
Have you already resolved this problem?
I met the same problem and I don't know how to solve this.
I have tried all solutions mentioned before but I failed.Please help me
