### ISSUE TITLE
Kinetics-400 test label 

### ISSUE THREAD

**Issue by 117kyjin** [activitynet/ActivityNet#36]
I can find kinetics-600 holdout test and test label in deepmind website. (https://deepmind.com/research/open-source/open-source-datasets/kinetics/)

However, I cannot find kinetics-400 test label. Where can I find the kinetics-400 test label?

**Comment by escorciav** [comment]
We are truly sorry for the late reply.  Please contact the responsibles of the [dataset](https://deepmind.com/research/open-source/open-source-datasets/kinetics/). Unfortunatly, we (ActivityNet team) are only hosting the Kinetics data (URLs, and labels) as part of the [ActivityNet Challenge](http://activity-net.org/challenges/2018/challenge.html).

Closing as the request is out of our hands.
