### ISSUE TITLE
Some videos of ActivityNet1.3 are not available

### ISSUE THREAD

**Issue by hjeun** [activitynet/ActivityNet#37]
I am trying to ActivityNet1.3 with crawler, but some videos are not downloaded.
Could you check how many videos in ActivityNet1.3 are now available?

**Comment by HumamAlwassel** [comment]
Hi Hyunjun

My apologies for the very delayed response. 
Thank you for your interest in ActivityNet. To accommodate all different data requests, we have created a Google form to give a 7-day-access to a full copy of ActivityNet videos on Google and Biadu Drives. Please fill [this form](https://forms.gle/1TC3aBtVCX7ySbo46) to get a copy of the full dataset. 

Cheers,
Humam
