### ISSUE TITLE
Pose estimation dataset

### ISSUE THREAD

**Issue by jhagege** [activitynet/ActivityNet#39]
Hi, are you aware of recent existing datasets with pose-estimation on any of the Kinetics datasets ? 
Thanks.

**Comment by escorciav** [comment]
That would be cool. Unfortunately, I have seen it yet.

I remember that some participants from ICL pitched that idea in our 2017-challenge. Probably Joao Carreira from DeepMind is keeping track on this carefully.

@cabaf @HumamAlwassel, are you aware of this?

I will close the issue as it's not related to ActivityNet. Pls keep the discussion ongoing as it's of my interest 😉
