### ISSUE TITLE
How to extract frames

### ISSUE THREAD

**Issue by VectorYoung** [activitynet/ActivityNet#41]
Hi, I found reading from the original .mp4 videos is very slow. Do I need to extract every frame in each video and read the RGB frames directly? If yes, do you have a script to do that? Thanks very much.

**Comment by escorciav** [comment]
Thanks for your interest in our work. I am sorry to hear you struggling.

- Regarding the frame extraction, you may be interested in the following projects. Use the one that fits your needs and knowledge the best.
    - call ffmpeg through python subprocess, [@escorciav/video-utils](https://github.com/escorciav/video-utils/)
    - Python bindings for FFmpeg, [ffmpeg-python](https://github.com/kkroening/ffmpeg-python)
    - Library to efficient loading of "videos" through images, [gulpio](https://github.com/TwentyBN/GulpIO).
    - Library for video loading using GPU, [nvvl](https://github.com/NVIDIA/nvvl).

Unfortunately, I can't give you any hint about why your approach is slow. We will try to upload frames soon to reduce the barrier for working with ActivityNet.

**Comment by escorciav** [comment]
You can find the frames extracted at 5FPS - 320x240 [here](https://drive.google.com/file/d/12YOTnPc4zCwum_R9CSpZAI9ppAei8KMG/view?usp=sharing) (~200GB).

Closing the issue as the previous answer addressed the question. Please let me know if that's not the case.

**Comment by VectorYoung** [comment]
@escorciav Thanks very much for your reply. I am trying to train my model on Kinetics 400. But I found that reading from the original .mp4 file is very slow. I saw some people saying that training on the extracted frames will be faster so I am trying to extract the frames in Kinetics 400 videos. But I have some concerns about that. For example, do I need to extract every frame in a video? Do I need to resize the frames to some size? Thanks a lot for your help.

**Comment by escorciav** [comment]
Sorry for the late reply. I forgot to flip the message as unread.
It really depends on your hardware constraints, and the task you want to tackle. Multiple papers working in classification process videos at 25FPS, thus extracting every frame will demand more storage. Similarly, many people working in classification are using receptive fields ranging from 224-256 pixels. Therefore, frames with HD resolution will require more storage and reduce the throughput of your data loader/feeder.
