### ISSUE TITLE
File command_list.txt does not exists.

### ISSUE THREAD

**Issue by gabir-yusuf** [activitynet/ActivityNet#43]
I need to download Activitynet_1.3 dataset so I add the json file in the current directory and run these commands:
`mkdir Dataset`
`chmod +x fetch_activitynet_videos.sh`
`./fetch_activitynet_videos.sh Dataset activity_net.v1-X.json`
**but i got this error:** 
usage: run_crosscheck.py [-h] video_path ann_file output_filename
run_crosscheck.py: error: too few arguments
File command_list.txt does not exists.
Have a good day!

**Comment by escorciav** [comment]
@cabaf may be able to help or gives some directions on how to proceed

**Comment by cabaf** [comment]
Hi Gabir,

I noticed that you are passing as argument the file `activity_net.v1-X.json`. Is it the correct annotation filename?

As an alternative to using the script `fetch_activitynet_videos.sh`, you can instead run the following commands:
```
python run_crosscheck.py <path_to_video_dir> <path_to_json_file> <output_file>
bash <output_file>
```

Let us know if that help.

**Comment by worthlessFella** [comment]
Hi,

The insturctions say run with activity_net.v1-X.json as argument. I am not able to understand what is this file and from where I should get it?
