### ISSUE TITLE
can't download dataset?

### ISSUE THREAD

**Issue by iuhiyuh** [activitynet/ActivityNet#44]
Hi. help pls. thx

#### sudo python download.py /opt/kinetics/train_split/data/kinetics_train.csv /opt/kinetics/train_split
Traceback (most recent call last):
  File "download.py", line 10, in <module>
    from joblib import delayed
ImportError: No module named joblib

#### conda install joblib
Collecting package metadata: done
Solving environment: done
All requested packages already installed.

#### pip install joblib
Requirement already satisfied: joblib in /home/admin/.pyenv/versions/anaconda3-2018.12/envs/kinetics/lib/python2.7/site-packages (0.13.2)

**Comment by Uysim** [comment]
I am facing the same issue. Did you found the solution?

**Comment by escorciav** [comment]
Python 2.7 expired. Perhaps it's related to that. Good luck :)

Upgrade to Python 3, and try to figure it out the requirements manually :wink:
