### ISSUE TITLE
"timeout or by a memory leak.", UserWarning

### ISSUE THREAD

**Issue by zhangchennb** [activitynet/ActivityNet#46]
The program error is：/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
I have used vpn.
Please help me.

**Comment by escorciav** [comment]
We are sorry to hear that. Could you please indicate which program you are using?

**Comment by escorciav** [comment]
Closed due to inactivity
