### ISSUE TITLE
Handling the case of multiple labels

### ISSUE THREAD

**Issue by calledbymountains** [activitynet/ActivityNet#47]
There are some videos in Kinetics-600 dataset with multiple labels associated with them. How are such cases to be handled ? 

Example -  In the validation set the video file `dMzycn1d3qU_000000_000010.mp4` has following two labels associated with them as follows 

```
In [25]: df.loc['dMzycn1d3qU']                                                                           
Out[25]: 
                      label  time_start  time_end split
youtube_id                                             
dMzycn1d3qU  weaving fabric           1        11   val
dMzycn1d3qU   yarn spinning           0        10   val
```
All in all there are 8 such videos in the validation set. I enumerate them by their youtube IDs as below 

```
In [27]: df.groupby(level=0).filter(lambda x: len(x) > 1)                                                                                
Out[27]: 
                           label  time_start  time_end split
youtube_id                                                  
xnC3nngvLCo    cracking knuckles           7        17   val
xnC3nngvLCo        cracking neck          83        93   val
c9ZWYpxefXQ        cutting apple          64        74   val
SN5awGHfw9M  kicking soccer ball          36        46   val
SN5awGHfw9M  passing soccer ball          27        37   val
c9ZWYpxefXQ       peeling apples          14        24   val
Z03StBdQzog          sawing wood          17        27   val
CYGlFBgKZV0               sewing         102       112   val
CYGlFBgKZV0     threading needle         145       155   val
Z03StBdQzog   using circular saw          55        65   val
dMzycn1d3qU       weaving fabric           1        11   val
dMzycn1d3qU        yarn spinning           0        10   val



```

**Comment by escorciav** [comment]
Thanks for your interest in the challenge.

- Firstly, please note that the ActivityNet team only hosts the data crawler and evaluation tools of Kinetics-600. I would greatly recommend: (i) contacting the dataset maintainers for general inquiries regarding the Kinetics-600 dataset; (ii) reading previous papers and implementation.

- Could you please provide a code snippet to replicate the error (if any)?

- Regarding the evaluation, I think that the code can deal with multiple label as it's top-5 accuracy or error. @cabaf can confirm that.

**Comment by calledbymountains** [comment]
@escorciav @cabaf  I found that there are two different videos for the case I mentioned. They are named according to their time stamps.  So, I admit it as an error and hereby close this issue.

**Comment by escorciav** [comment]
No worries. Thanks for your interest again.
