### ISSUE TITLE
low

### ISSUE THREAD

**Issue by jeff62802217** [activitynet/ActivityNet#48]

**Comment by jeff62802217** [comment]
How can improve the speed of downloading of this dataset? It takes several hours but there are no videos in the folder where I download the kinetics-400_train.

**Comment by escorciav** [comment]
The speed depends on different factors:

- Your network

- Your storage device

- The number of CPU cores

If there isn't any video, you are likely facing an issue with the setup of the program or the way that you are using it. In this case, please be patient and debug it as a usual python program.

Once you are downloading videos, change the number of processes according to your system.

_How the program works?_
The program parallelizes single video jobs. A video job consists on, downloading a video (IO operation) follow by a trimming operation (CPU&IO operation). People with decent internet connection and lot of CPU cores, afford to process multiple videos concurrently.

**Comment by escorciav** [comment]
Closing as it has been a while since last reply
