### ISSUE TITLE
where is command_list.txt file to download?

### ISSUE THREAD

**Issue by Atrin4000** [activitynet/ActivityNet#49]
When I run the last line it show me following error:"File command_list.txt does not exists."

Thanks

**Comment by JJBOY** [comment]
me too

**Comment by JJBOY** [comment]
Now I know how slove this problem. You should first download the json file from http://activity-net.org/download.html and then repalce the "activity_net.v1-X.json" in the command with the file name you download. Then you can get the "command_list.txt".
Hope its helpful for you.

**Comment by escorciav** [comment]
Thanks for your interest in our work and sorry for the late reply.

If you are interested in downloading ActivityNet dataset. You can sign up to download it from [here](https://docs.google.com/forms/d/e/1FAIpQLSeKaFq9ZfcmZ7W0B0PbEhfbTHY41GeEgwsa7WobJgGUhn4DTQ/viewform). You must read the terms and conditions.

**Comment by escorciav** [comment]
Closing due to no response was provided
