### ISSUE TITLE
What if I do not Anaconda with Kinetics downloader script?

### ISSUE THREAD

**Issue by antran89** [activitynet/ActivityNet#5]
Hi,

I am open this issue to request a feature for setting up an environment for the user, who do not use Anaconda.

```
conda env create -f environment.yml
source activate kinetics
```

Best regards,
An

**Comment by HumamAlwassel** [comment]
Dear An,

We appreciate your interest in ActivityNet and the ongoing challenge. We provide a __conda__ environment, [environment.yml](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/environment.yml), to get you started and up-to-speed.
Feel free to create your own deployment environment and to kindly post your solution here for people who do not want to use conda.

Have a great time pushing the limits of activity understanding.

Side comment: conda != anaconda, take a look at [these myths around conda](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/).

**Comment by antran89** [comment]
Thank @HumamAlwassel your kind information. I used normal Python and pip.

```
sudo apt-get install x264
sudo apt-get install ffmpeg
sudo pip install --upgrade youtube-dl
```
I think your solution with conda is great, I will get to know conda.
