### ISSUE TITLE
How to get the missing video of kinetics-400

### ISSUE THREAD

**Issue by chenbohua3** [activitynet/ActivityNet#52]
After downloading kinetics-400 training set using the script, only around 220000 videos can be obtained. How can I get the missing videos? I only use it for academic purpose:)

**Comment by escorciav** [comment]
Thanks for your interest in Kinetics.

Please vote favorably [this comment](https://github.com/activitynet/ActivityNet/issues/28#issuecomment-480499548) make a strong case with the dataset maintainers.

Closing the issue as it's not related to ActivityNet and out of our scope.
