### ISSUE TITLE
Can't find the file called '{dataset_split}.csv' in official website

### ISSUE THREAD

**Issue by zhou07** [activitynet/ActivityNet#53]
Hi,
I can't find the files called '{dataset_split}.csv' in official website, there is not any csv file in official website. So, Where can I get the the files called '{dataset_split}.csv'?

**Comment by escorciav** [comment]
Thanks for your interest in our work, and we are sorry for the late reply.

Could you please tell us which program you are trying to download?

**Comment by Ichchhayakants** [comment]
kinetics

**Comment by gurkirt** [comment]
have a look here, https://github.com/gurkirt/kinetics-download-prep

**Comment by escorciav** [comment]
It seems the link is broken on the Kinetics website. I just drop an email to the dataset maintainers.

Please reach them directly for this kind of errors.

**Comment by escorciav** [comment]
If you click on "View source", you will get Kinetics-700.

c.c. @Ichchhayakants
