### ISSUE TITLE
Not able to download videos

### ISSUE THREAD

**Issue by Pankaj01998** [activitynet/ActivityNet#54]
I am trying this code on google colab. When I run it, I downloads some videos at the beginning but after that, it is not any downloading videos.

I checked the status of it in the status list, it shows me following

"ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

SO please help me in it

**Comment by hawkcoder** [comment]
I have the same problem too,

![image](https://user-images.githubusercontent.com/5601204/63177333-45235f80-c07a-11e9-85df-eed76b3001ae.png)

**Comment by escorciav** [comment]
Closing this as we will track it in #51
