### ISSUE TITLE
Could you please provide the C3D features pre-trained models?

### ISSUE THREAD

**Issue by IvanFei** [activitynet/ActivityNet#55]
Hi, 
Thank you for providing the c3d features in [dense video caption dataset](http://activity-net.org/challenges/2017/download.html#c3d).
I want to test the published models with local dataset. And it's necessary for us to know the pre-trained model which use to extract the C3D features. So, I wander if you could provide the pre-trained model? 
Thank you anyway.

**Comment by IvanFei** [comment]
> Hi,
> Thank you for providing the c3d features.
> I want to test the published models with local dataset. And it's necessary for us to know the pre-trained model which use to extract the C3D features. So, I wander if you could provide the pre-trained model?
> Thank you any way.

**Comment by escorciav** [comment]
Thk for your interest in our work.

@cabaf should have a precise answer. I think he used C3D v1.0 pre-trained in Sports-1M.

Note that as part of the latest AcitivityNet challenge more recent features were released. Check it out [here](https://drive.google.com/open?id=1qzMC0XXkK3-lUUfutFsqY9vmRLTx_Vpw), [details here](https://drive.google.com/file/d/1qQyDGgBMp3tZ3E-0e641jzKTmOFCbKbD/view)

**Comment by IvanFei** [comment]
@escorciav 
I really appreciate all your help. 

With your help, I found the C3D v1.0 pre-trained model in Sports-1M : [Pre-Trained Model](http://vlg.cs.dartmouth.edu/c3d/)

Thank you very much .
^ . ^

**Comment by escorciav** [comment]
Closing as request was attended
