### ISSUE TITLE
Cant download videos possibily because of Error 429

### ISSUE THREAD

**Issue by ambekarsameer96** [activitynet/ActivityNet#58]
I tried using this repo to download the Kinetics dataset but I am unable to download. Can you please check.

**Comment by OysterSecret** [comment]
Same issues after I downloaded part of it.

**Comment by escorciav** [comment]
Please provide more details to identify the kind of issue.

If you are facing problems, due to many requests to the Youtube platform, that's out of our control. Individuals are trying to make the videos publicly available. Perhaps you could reach them politely and gratefully.

**Comment by escorciav** [comment]
Closing due to lack of traction
