### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 408: Request Timeout

### ISSUE THREAD

**Issue by apapadaki** [activitynet/ActivityNet#59]
it seems that  the link: http://ec2-52-11-11-89.us-west-2.compute.amazonaws.com/challenge17/api.py is down. Would it be possible to fix that please?

**Comment by chenyangcn** [comment]
I also have the same problem. Can you solve it? @apapadaki

**Comment by chenyangcn** [comment]
I also have the same problem. Have you solved it? @apapadaki

**Comment by apapadaki** [comment]
No... I think it is either because many people try to access that link or because it has reached the daily limit...

**Comment by cabaf** [comment]
Hey @apapadaki thanks for reporting!

We have fixed the issue with our latest commit. The API now faces the following url:
[http://ec2-52-25-205-214.us-west-2.compute.amazonaws.com/challenge19/api.py](url)

Please make sure to pull the latest changes before running the evaluation code.

**Comment by yagmurshn** [comment]
I've retrieved the most recently updates for the code side, yet the get_blocked_videos function continues to raise a **[Errno 110] Connection timed out error** for the subsequent API URLs.
http://ec2-52-25-205-214.us-west-2.compute.amazonaws.com/challenge19/api.py
http://ec2-52-11-11-89.us-west-2.compute.amazonaws.com/challenge17/api.py
