### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

### ISSUE THREAD

**Issue by chenyangcn** [activitynet/ActivityNet#60]
it seems that the link: http://ec2-52-25-205-214.us-west-2.compute.amazonaws.com/challenge19/api.py is down. Would it be possible to fix that please?

**Comment by Valarrrrr** [comment]
I also have the same problem. Have you solved it? @chenyangcn

**Comment by chenyangcn** [comment]
> I also have the same problem. Have you solved it? @chenyangcn

The code updated in the latest release has fix the problem

**Comment by Valarrrrr** [comment]
Thank you for your respons. But I have download the latest released code and still have the error that 'ValueError: No JSON object could be decoded'. Do you know what is the problem. Thank you!
