### ISSUE TITLE
can't download videos due to TypeError

### ISSUE THREAD

**Issue by lepoeme20** [activitynet/ActivityNet#61]
Hi, thanks for your code.
I tried to download kinetics real videos from youtube using code.
But I faced error as below:
`TypeError: Object of type 'bytes' is not JSON serializable`

How can I fix the error?

Please reply to this issue.

**Comment by SiftingSands** [comment]
If anyone else encounters this issue, decode from bytes to ASCII on line 133 of download.py
`status = tuple([clip_id, downloaded, log.decode('ascii')])`
