### ISSUE TITLE
Some videos cannot download

### ISSUE THREAD

**Issue by liuxuebo0** [activitynet/ActivityNet#62]
After I download kinetics-400 validation set, the 'download_report.json' shows 'ERROR: Content Warning\nIf the owner of this video has granted you access, please sign in.\n       This video is private.\n', only 18076 if 19906 videos are downloaded successful, how to deal with this problem? Thanks.

**Comment by Anirudh257** [comment]
You can't download private videos.

**Comment by escorciav** [comment]
I'm sorry, but this is out of the scope of the repo. As such, I'm closing the issue.
Subscribe to #68 #28 where people have commented about the same problem.

**Comment by Anirudh257** [comment]
Sure
