### ISSUE TITLE
it seems that the link: http://ec2-52-25-205-214.us-west-2.compute.amazonaws.com/challenge19/api.py is down. 

### ISSUE THREAD

**Issue by Valarrrrr** [activitynet/ActivityNet#64]

**Comment by Gary-Shi** [comment]
Yes, I cannot connect to this url, either.

**Comment by escorciav** [comment]
I'm sorry about your situation, but it's unclear what's your problem. Closing due to lack of clear information.

In the future, we greatly appreciate using (i) the title/subject box to describes the issue, (ii) the comment box to post the details. Not the other way around.
