### ISSUE TITLE
resnet152_features

### ISSUE THREAD

**Issue by liyue2ppy** [activitynet/ActivityNet#65]
Hi, I would like to know how long it takes for the features to finish uploading, which concerns the strategy of my experiment. 
What's more, can you tell me the base accuracy of classification when using these features? I didn't find the related information on official website.

**Comment by escorciav** [comment]
Hi,

Thanks for your interest in the dataset. I'm truly sorry for the delay.

Could you please clarify the questions?

- The ResNet152 of ActivityNet is [here](https://drive.google.com/file/d/1qzMC0XXkK3-lUUfutFsqY9vmRLTx_Vpw/view). Please see the details [here](https://drive.google.com/file/d/1qQyDGgBMp3tZ3E-0e641jzKTmOFCbKbD/view).

- We didn't evaluate classification or localization accuracy with these features. Feel free to report your findings here.

Cheers,
Victor
