### ISSUE TITLE
ModuleNotFoundError: No module named 'fvcore.common.registry'

### ISSUE THREAD

**Issue by yinruiying** [activitynet/ActivityNet#66]
Thanks for your nice work!
I have installed all of libraries following your install.md. But when i run "python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml NUM_GPUS 1 TRAIN.BATCH_SIZE 8 SOLVER.BASE_LR 0.0125 DATA.PATH_TO_DATA_DIR path_to_your_data_folder", i got the following error:
![image](https://user-images.githubusercontent.com/21331073/72673475-fd2fbb00-3aa5-11ea-91ff-5bef72ff8e92.png)
I find the "fvcore" in my installed packages:
![image](https://user-images.githubusercontent.com/21331073/72673508-6fa09b00-3aa6-11ea-88a9-3536df866ac3.png)

**Comment by escorciav** [comment]
I'm sorry but this is out of the scope of the repo. As such I'm closing the issue. Check out StackOverflow for help.
