### ISSUE TITLE
Poor Temporal Annotations

### ISSUE THREAD

**Issue by zaie** [activitynet/ActivityNet#69]
The temporal action annotations of Activitynet are so poor that I can not trust them. I believe the data needs to be relabelled. For example, temporal annotations in video 'OiL6Aj0gC14', 'onBAyGhqubg' and 'optJ47P_5Ys'. Is there any reason for that?

**Comment by zaie** [comment]
The temporal action annotations of Activitynet are so poor that I can not trust them. I believe the data needs to be relabelled. For example, temporal annotations in video 'OiL6Aj0gC14', 'onBAyGhqubg' and 'optJ47P_5Ys'. Is there any reason for that?

**Comment by cabaf** [comment]
Thanks for the feedback about the quality of temporal annotations. While we have conducted two rounds of cleaning already, we are open to contributions from the community to improve the dataset quality further. Please send your feedback, and potential annotation fixes, to the dataset maintainers via email.
