### ISSUE TITLE
Incomplete Dataset

### ISSUE THREAD

**Issue by abnera** [activitynet/ActivityNet#7]
Hello

I have used this crawler to download the full Kinetics dataset for the benchmark of algorithms. However, when using the script some of the videos are not being downloaded with the crawler. After exploring the JSON progress logger the following errors arise.

Errors:
ERROR: fC4iVtuX22Q: YouTube said: This video does not exist.ERROR: fC4iVtuX22Q: YouTube said: This video does not exist.
ERROR: xxq3FXccFrM: YouTube said: Please sign in to view this video.
ERROR: yIELmF1k2no: YouTube said: This video has been removed by the user.

Three different types of errors that need to be addressed. In total there were about ~50 videos I was unable to download.

**Comment by HumamAlwassel** [comment]
Hello! Thank you for your interest in ActivityNet, and we apologize for the late response. We had similar requests from other participants about the missing videos from Kinetics. Unfortunately, between the time the dataset was created at DeepMind and the time ActivityNet challenge organizers received it for the challenge, about 6000 videos of the training/validation split were removed from YouTube. We don't have these missing videos in our back-up copy of the dataset on ActivityNet challenge servers. I'm sorry that we aren't able to help you with this request, but we hope that this small percentage of the dataset won't affect your model training. As for the testing subset, please note that our evaluation server computes the performance only on the test videos that are still available on YouTube at the time of the submission is made. The server crawls YouTube on a daily basis to update the missing videos list. Once again, we apologize for not being able to help you with this request. We look forward for your challenge submissions.

Best Regards,
Humam
