### ISSUE TITLE
As part of this year ActivityNet Challenge, we are providing new features extracted by other researchers.

### ISSUE THREAD

**Issue by mc261670164** [activitynet/ActivityNet#79]
As part of this year ActivityNet Challenge, we are providing new features extracted by other researchers.

ResNet-152 features and frames [here](http://activity-net.org/challenges/2019/tasks/anet_localization.html#resources). Please refer to the README for details about the extraction.

You can also apply to download the videos of the database [here](https://forms.gle/1TC3aBtVCX7ySbo46). Make sure that you read the fine details.

_Originally posted by @escorciav in https://github.com/activitynet/ActivityNet/issues/8#issuecomment-495928116_

**Comment by mc261670164** [comment]
Hi  @escorciav, Could you tell me how can I extract the features like the dataset of "ActivityNet Captions". Or in wich README has this problem introduced? Thank you very much!

**Comment by escorciav** [comment]
Thanks for your interest in our work

- The links that you mentioned are working for me.

- ActivityNet Captions re-used the videos of ActivityNet. Thus, you can use the features that you found without issues.

- Please cite the corresponding papers mentioned [here](https://drive.google.com/file/d/1qQyDGgBMp3tZ3E-0e641jzKTmOFCbKbD/view).

I'm sorry if I didn't understand the question.

**Comment by mc261670164** [comment]
Emmm,  @escorciav thanks for your reply, I want extract the features from my own videos. The TXT in the Google Drive link you offered, I find the link "https://github.com/escorciav/feature-extraction/blob/corpus-moment-retrieval/pthv_models.py" can't be visited now, could you give me a new one please?

**Comment by escorciav** [comment]
That would require some time, as I haven't released the repo. Please open the issue in [this repo](https://github.com/escorciav/moments-retrieval-page).

I will close the issue as your request is out of the scope of this project.
