### ISSUE TITLE
C3D features

### ISSUE THREAD

**Issue by ksharsha** [activitynet/ActivityNet#8]
I am unable to figure out how to read the C3D features from the files present in http://activity-net.org/challenges/2016/download.html . Can you please explain the same?

**Comment by escorciav** [comment]
Hi @ksharsha, did you find a solution?

**Comment by escorciav** [comment]
This a rough example illustrating the content in the HDF5.
- Copy-paste and run this program.

- Follow the comments to parse the features.

```
import h5py

filename = 'activitynet_v1-3.hdf5'
fid = h5py.File(filename, 'r')
video_lst = list(fid.keys())
print('Number of videos in the container: ', len(video_lst))
ith = 5
print('feat of {}-th video: {}'.format(ith, video_lst[ith]))
# This line clearly shows that the features are stored as Group/Dataset
feat_video_ith = fid[video_lst[ith]]['c3d_features'][:]
print('shape of features: {}'.format(feat_video_ith.shape))
print('It should be a 2D array with the second axis == 500 for all the videos')

print('Note that the video_lst comes from a ".keys()", thus the order of might change after every trial. However, I did not noticed that in my version of python and h5py.')
fid.close()
```

You need to install h5py and its dependencies. You could use anaconda or miniconda for this:
`conda create -n parse-c3d-anet python=3.6 h5py`

This is an academic dummy example. Read about [h5py]() or the library of your preference for optimized ways to access the data.

**Comment by BKHMSI** [comment]
@escorciav can you please tell what is the FPS used for the C3D features in http://activity-net.org/challenges/2016/download.html? I coudn't find it mentioned anywhere online

**Comment by escorciav** [comment]
Those features were extracted every 8 frames.
@cabaf, do you have more info about it?
I think we don't have the frames anymore to provide precise FPS.

**Comment by BKHMSI** [comment]
Yes, I am asking because I am trying to use the published C3D features alongside features from other feature extractors, and for that I need to get the corresponding frames in the video given that the they might have different FPS rates, any information would be appreciated. 

Thanks!

**Comment by BKHMSI** [comment]
of-course
- We are a bit resource constrained, so we would prefer avoid computing stuff again whenever possible. Therefore the C3D features were extremely helpful to speedup the training process.

**Comment by cabaf** [comment]
Unfortunately, we don't have a backup of the videos used to extract the C3D features. Thus, we can't provide the exact frame-rate.

**Comment by BKHMSI** [comment]
Ok, thank you for your reply

**Comment by zhangzhizz** [comment]
@ksharsha Hi，do you know how to open C3D feature on the web : http://activity-net.org/challenges/2016/download.html

**Comment by nayyeraafaq** [comment]
Hi everyone, 
I want to use ActivityNet_Captions dataset. But I can't find videos. What is given is C3D features of the videos and their annotations. Can anyone share the videos link please?

**Comment by BKHMSI** [comment]
Hi @nayyeraafaq. You can find the dataset [here](https://cs.stanford.edu/people/ranjaykrishna/densevid/captions.zip). It's a JSON file with the video ids and their corresponding captions with timestamps. The id is part of the video's URL, so you can find the video like this: https://www.youtube.com/watch?v={id}  
I hope that helps!

**Comment by BKHMSI** [comment]
Hi @nayyeraafaq. You can find the dataset [here](https://cs.stanford.edu/people/ranjaykrishna/densevid/captions.zip). It's a JSON file with the video ids and their corresponding captions with timestamps. The id is part of the video's URL, so you can find the video like this: https://www.youtube.com/watch?v={id}  
I hope that helps!

**Comment by escorciav** [comment]
As part of this year ActivityNet Challenge, we are providing new features extracted by other researchers.

Take a look at them [here](http://activity-net.org/challenges/2019/tasks/anet_localization.html#resources).

You can also apply to download the videos of the database [here](https://forms.gle/1TC3aBtVCX7ySbo46). Make sure that you read the fine details.

**Comment by MyWorldN** [comment]
Hi, @ksharsha BKHMSI
Kindly share the training testing and validation labels and splits.

Thank you

**Comment by zhyj3038** [comment]
Hi, I found for a video, the number of  frames and the number of C3D features  confused me.  eg. for video "v_zvoDDqvr2DU", the "video_info.csv" file said numFrame is 558, but the featru shape  is (68, 500),  but i think the correct shape is (69,500).  the other video's feature shape all less the correct shape than 1.
