### ISSUE TITLE
Script to compute video-mAP for spatio-temporal action localization (AVA) task

### ISSUE THREAD

**Issue by ptirupat** [activitynet/ActivityNet#83]
Hello,

Thank you for providing the script to computer frame-mAP for the AVA task. Is it possible to use this script to also compute video-mAP? If so, please let me know how. Is there any plan to add a separate script for video-mAP to this project?

**Comment by escorciav** [comment]
Thanks! Please reach out to AVA-maintainers in their communication channel, google-groups.
