### ISSUE TITLE
OSError: File b'{dataset_split}.csv' does not exist

### ISSUE THREAD

**Issue by igor71** [activitynet/ActivityNet#9]
Hi!!
I'm trying to download Kinetics database on Ubuntu Server 16.04.01,  but getting following error:

> OSError: File b'{dataset_split}.csv' does not exist

I've performed all steps in README.md file, but on the lats step:

> mkdir DATASETS; python download.py {dataset_split}.csv DATASETS

I'm getting errors:

```
yi@server-30:~/Kinetics/ActivityNet/Crawler/Kinetics$ mkdir DATASETS; python download.py {dataset_split}.csv DATASETS
Traceback (most recent call last):
  File "download.py", line 192, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 154, in main
    dataset = parse_kinetics_annotations(input_csv)
  File "download.py", line 142, in parse_kinetics_annotations
    df = pd.read_csv(input_csv)
  File "/home/yi/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/yi/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yi/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/home/yi/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/yi/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1213, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 358, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3427)
  File "pandas/parser.pyx", line 628, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6861)
OSError: File b'{dataset_split}.csv' does not exist
```
What I'm doing wrong?

**Comment by HumamAlwassel** [comment]
Hi! Thank you for your interest in ActivityNet. To resolve your issue, please replace `{data_split}.csv` in the last command with the _path_ to the CSV data file for the dataset split you want to download. For example, if you want to download the training subset, run the command 
`mkdir train_split; python download.py data/kinetics_train.csv train_split`
and if you want to download the validation subset, run the command 
`mkdir val_split; python download.py data/kinetics_val.csv val_split`
and so on.

Cheers,
Humam

**Comment by igor71** [comment]
Thanks for the quick respond! Now it's working... If it possible... how I can check the progress of downloading?

**Comment by HumamAlwassel** [comment]
I don't think we build that feature in the script, but you can check how many files are downloaded in the destination folder compared to the number of rows in the CSV file. That should give you an idea on how much progress you made.

**Comment by igor71** [comment]
Hi, I've left download for weekend but it seems that downloader not working... I've started download two days ago with command` mkdir val_split; python download.py data/kinetics_val.csv val_split` ... Today I've checked number of files under directory val_split, there was 400 files and size of this directory 1.6MB... So something goes wrong, in spite of download command looks like still running with no errors. Do you have any clue how to check whats wrong? Thank you in advance, Igor

**Comment by HumamAlwassel** [comment]
I'm sorry Igor - I cannot tell what might have gone wrong on your side. Can you check the dates of when these 400 files got created on your machine? It might be the case that your Internet connection is slow or got cut off in the middle of the download.

**Comment by igor71** [comment]
Hi, Thank you for respond. I don't think it linked to the internet speed (we have 100MBit/sec download speed)... I've removed val_split folder yesterday and started download again with the same command. Today morning I  checked the val_split folder ( `ls -lR | grep ^d | wc -l` ), it contain 400 empty folders (not files, my bad...) 4.0K each one, in summary 1.6MB and no files created inside those folders. The download command still running in other session, exactly in the same state I leave it yesterday...

**Comment by igor71** [comment]
I figured out what was wrong... for some reason ffmpeg-3.1.3-0 wasn't installed properly. Once I've reinstalled it, download started properly.
