### ISSUE TITLE
C3D features download

### ISSUE THREAD

**Issue by hongruijia** [activitynet/ActivityNet#94]
Hi, I wanna know how to download the hdf5 files. When I open the URL http://ec2-52-25-205-214.us-west-2.compute.amazonaws.com/data/challenge16/features/c3d/activitynet_v1-3.part-00, a 404 ERROR happened.
![image](https://github.com/activitynet/ActivityNet/assets/91206112/6c67f5c1-5cdf-4abc-a9a6-15c0eb8dcbf9)

**Comment by onlyonewater** [comment]
+1, the same problem!!

**Comment by escorciav** [comment]
Those feautres are oudated. Kindly search in the repo as I pointed out for a more modern version of visual features.

If you reviewer or AC/editor complains, feel free to reference this issue in the Appendix of your paper. Letting them know that I said:
"Stop being overrigorous! I'm also part of the rigor police & you're stepping in my jurisdiction"

😆

**Comment by hongruijia** [comment]
Thank you for your reply!
