### ISSUE TITLE
how to use the PCA to reduce the dimension?

### ISSUE THREAD

**Issue by onlyonewater** [activitynet/ActivityNet#95]
hi, authors, @escorciav I noticed that you use PCA to reduce the feature dimension from 4096 to 500, due to the feature of each video is a 2d tensor, so I want to know how to use PCA to reduce the original feature dimension from (num_frames, original_dim) to (num_frames, new_dim). And using the PCA tool could drop some information in this process, so I think this step may hurt the model's performance. So I want to know how to use the PCA to reduce the video feature dimension. thanks!!!

**Comment by escorciav** [comment]
That step is optional. As mentioned in another issue, kindly search in the repo for a more updated version of pre-computed features.

Context: Kindly remind that you're asking for details about the pre-historic era of video understanding with deep learning 😆 . C3D is the AlexNet of video modeling.

_Why did we do that?_
- I didn't know the impact of the frame sampling. AFAIK (in 2023), the community has noticed that the impact is minor & nearly irrelevant for practical purposes in TAL on multiple datasets (THUMOS14, ActivityNet & HACS).
- As such, I extracted features in a dense manner. As I didn't have enough storage, PCA was a good hammer in my toolbox for the problem at hand 🧰 .
- I had taken a numerical optimization class, and I wanted to use the stuff that I learned.

Good luck!
